package EvoConditions;

public enum BiomeTypeList {

    the_void("minecraft:the_void"),
    plains("minecraft:plains"),
    sunflower_plains("minecraft:sunflower_plains"),
    snowy_plains("minecraft:snowy_plains"),
    ice_spikes("minecraft:ice_spikes"),
    desert("minecraft:desert"),
    swamp("minecraft:swamp"),
    mangrove_swamp("minecraft:mangrove_swamp"),
    forest("minecraft:forest"),
    flower_forest("minecraft:flower_forest"),
    birch_forest("minecraft:birch_forest"),
    dark_forest("minecraft:dark_forest"),
    old_growth_birch_forest("minecraft:old_growth_birch_forest"),
    old_growth_pine_taiga("minecraft:old_growth_pine_taiga"),
    old_growth_spruce_taiga("minecraft:old_growth_spruce_taiga"),
    taiga("minecraft:taiga"),
    snowy_taiga("minecraft:snowy_taiga"),
    savanna("minecraft:savanna"),
    savanna_plateau("minecraft:savanna_plateau"),
    windswept_hills("minecraft:windswept_hills"),
    windswept_gravelly_hills("minecraft:windswept_gravelly_hills"),
    windswept_forest("minecraft:windswept_forest"),
    windswept_savanna("minecraft:windswept_savanna"),
    jungle("minecraft:jungle"),
    sparse_jungle("minecraft:sparse_jungle"),
    bamboo_jungle("minecraft:bamboo_jungle"),
    badlands("minecraft:badlands"),
    eroded_badlands("minecraft:eroded_badlands"),
    wooded_badlands("minecraft:wooded_badlands"),
    meadow("minecraft:meadow"),
    cherry_grove("minecraft:cherry_grove"),
    grove("minecraft:grove"),
    snowy_slopes("minecraft:snowy_slopes"),
    frozen_peaks("minecraft:frozen_peaks"),
    jagged_peaks("minecraft:jagged_peaks"),
    stony_peaks("minecraft:stony_peaks"),
    river("minecraft:river"),
    frozen_river("minecraft:frozen_river"),
    beach("minecraft:beach"),
    snowy_beach("minecraft:snowy_beach"),
    stony_shore("minecraft:stony_shore"),
    warm_ocean("minecraft:warm_ocean"),
    lukewarm_ocean("minecraft:lukewarm_ocean"),
    deep_lukewarm_ocean("minecraft:deep_lukewarm_ocean"),
    ocean("minecraft:ocean"),
    deep_ocean("minecraft:deep_ocean"),
    cold_ocean("minecraft:cold_ocean"),
    deep_cold_ocean("minecraft:deep_cold_ocean"),
    frozen_ocean("minecraft:frozen_ocean"),
    deep_frozen_ocean("minecraft:deep_frozen_ocean"),
    mushroom_fields("minecraft:mushroom_fields"),
    dripstone_caves("minecraft:dripstone_caves"),
    lush_caves("minecraft:lush_caves"),
    deep_dark("minecraft:deep_dark"),
    nether_wastes("minecraft:nether_wastes"),
    warped_forest("minecraft:warped_forest"),
    crimson_forest("minecraft:crimson_forest"),
    soul_sand_valley("minecraft:soul_sand_valley"),
    basalt_deltas("minecraft:basalt_deltas"),
    the_end("minecraft:the_end"),
    end_highlands("minecraft:end_highlands"),
    end_midlands("minecraft:end_midlands"),
    small_end_islands("minecraft:small_end_islands"),
    end_barrens("minecraft:end_barrens"),
    legacy_frozen_ocean("minecraft:legacy_frozen_ocean"),
    deep_warm_ocean("minecraft:deep_warm_ocean"),
    stone_beach("minecraft:stone_beach"),
    cold_beach("minecraft:cold_beach"),
    forest_hills("minecraft:forest_hills"),
    birch_forest_hills("minecraft:birch_forest_hills"),
    birch_forest_mutated("minecraft:birch_forest_mutated"),
    birch_forest_hills_mutated("minecraft:birch_forest_hills_mutated"),
    roofed_forest("minecraft:roofed_forest"),
    roofed_forest_mutated("minecraft:roofed_forest_mutated"),
    jungle_hills("minecraft:jungle_hills"),
    jungle_mutated("minecraft:jungle_mutated"),
    jungle_edge("minecraft:jungle_edge"),
    jungle_edge_mutated("minecraft:jungle_edge_mutated"),
    bamboo_jungle_hills("minecraft:bamboo_jungle_hills"),
    taiga_hills("minecraft:taiga_hills"),
    taiga_mutated("minecraft:taiga_mutated"),
    cold_taiga("minecraft:cold_taiga"),
    cold_taiga_hills("minecraft:cold_taiga_hills"),
    cold_taiga_mutated("minecraft:cold_taiga_mutated"),
    mega_taiga("minecraft:mega_taiga"),
    mega_taiga_hills("minecraft:mega_taiga_hills"),
    redwood_taiga_mutated("minecraft:redwood_taiga_mutated"),
    redwood_taiga_hills_mutated("minecraft:redwood_taiga_hills_mutated"),
    mushroom_island("minecraft:mushroom_island"),
    mushroom_island_shore("minecraft:mushroom_island_shore"),
    swampland("minecraft:swampland"),
    swampland_mutated("minecraft:swampland_mutated"),
    savanna_mutated("minecraft:savanna_mutated"),
    savanna_plateau_mutated("minecraft:savanna_plateau_mutated"),
    desert_hills("minecraft:desert_hills"),
    desert_mutated("minecraft:desert_mutated"),
    ice_plains("minecraft:ice_plains"),
    ice_mountains("minecraft:ice_mountains"),
    ice_plains_spikes("minecraft:ice_plains_spikes"),
    extreme_hills("minecraft:extreme_hills"),
    extreme_hills_plus_trees("minecraft:extreme_hills_plus_trees"),
    extreme_hills_mutated("minecraft:extreme_hills_mutated"),
    extreme_hills_plus_trees_mutated("minecraft:extreme_hills_plus_trees_mutated"),
    extreme_hills_edge("minecraft:extreme_hills_edge"),
    mesa("minecraft:mesa"),
    mesa_plateau("minecraft:mesa_plateau"),
    mesa_plateau_mutated("minecraft:mesa_plateau_mutated"),
    mesa_plateau_stone("minecraft:mesa_plateau_stone"),
    mesa_plateau_stone_mutated("minecraft:mesa_plateau_stone_mutated"),
    mesa_bryce("minecraft:mesa_bryce"),
    hell("minecraft:hell"),
    soulsand_valley("minecraft:soulsand_valley");

    private final String text;

    BiomeTypeList(String biome) {
        this.text = biome;
    }

    @Override
    public String toString() {
        return text;
    }
}
