package EvoConditions;

import java.util.ArrayList;
import java.util.Arrays;

public class constant_list {
    public static final ArrayList<String> moves_Array = new ArrayList<>(Arrays.asList(
            "Absorb", "Accelerock", "Acid", "Acid Armor", "Acid Spray", "Acrobatics", "Acupressure", "Aerial Ace",
            "Aeroblast", "After You", "Agility", "Air Cutter", "Air Slash", "Ally Switch", "Amnesia", "Anchor Shot",
            "Ancient Power", "Apple Acid", "Aqua Cutter", "Aqua Jet", "Aqua Ring", "Aqua Step", "Aqua Tail",
            "Arm Thrust", "Armor Cannon", "Aromatherapy", "Aromatic Mist", "Assist", "Assurance", "Astonish",
            "Astral Barrage", "Attack Order", "Attract", "Aura Sphere", "Aura Wheel", "Aurora Beam", "Aurora Veil",
            "Autotomize", "Avalanche", "Axe Kick", "Baby-Doll Eyes", "Baneful Bunker", "Barb Barrage", "Barrage",
            "Barrier", "Baton Pass", "Beak Blast", "Beat Up", "Behemoth Bash", "Behemoth Blade", "Belch", "Belly Drum",
            "Bestow", "Bide", "Bind", "Bite", "Bitter Blade", "Bitter Malice", "Blast Burn", "Blaze Kick",
            "Bleakwind Storm", "Blizzard", "Block", "Blue Flare", "Body Press", "Body Slam", "Bolt Beak", "Bolt Strike",
            "Bone Club", "Bone Rush", "Bonemerang", "Boomburst", "Bounce", "Branch Poke", "Brave Bird",
            "Breaking Swipe", "Brick Break", "Brine", "Brutal Swing", "Bubble", "Bubble Beam", "Bug Bite", "Bug Buzz",
            "Bulk Up", "Bulldoze", "Bullet Punch", "Bullet Seed", "Burn Up", "Burning Jealousy", "Calm Mind",
            "Camouflage", "Captivate", "Ceaseless Edge", "Celebrate", "Charge", "Charge Beam", "Charm", "Chatter",
            "Chilling Water", "Chilly Reception", "Chip Away", "Chloroblast", "Circle Throw", "Clamp",
            "Clanging Scales", "Clangorous Soul", "Clear Smog", "Close Combat", "Coaching", "Coil", "Collision Course",
            "Comet Punch", "Comeuppance", "Confide", "Confuse Ray", "Confusion", "Constrict", "Conversion",
            "Conversion 2", "Copycat", "Core Enforcer", "Corrosive Gas", "Cosmic Power", "Cotton Guard", "Cotton Spore",
            "Counter", "Court Change", "Covet", "Crabhammer", "Crafty Shield", "Cross Chop", "Cross Poison", "Crunch",
            "Crush Claw", "Crush Grip", "Curse", "Cut", "Dark Pulse", "Dark Void", "Darkest Lariat", "Dazzling Gleam",
            "Decorate", "Defend Order", "Defense Curl", "Defog", "Destiny Bond", "Detect", "Diamond Storm", "Dig",
            "Dire Claw", "Disable", "Disarming Voice", "Discharge", "Dive", "Dizzy Punch", "Doodle", "Doom Desire",
            "Double-Edge", "Double Hit", "Double Iron Bash", "Double Kick", "Double Shock", "Double Slap",
            "Double Team", "Draco Meteor", "Dragon Ascent", "Dragon Breath", "Dragon Claw", "Dragon Dance",
            "Dragon Darts", "Dragon Energy", "Dragon Hammer", "Dragon Pulse", "Dragon Rage", "Dragon Rush",
            "Dragon Tail", "Drain Punch", "Draining Kiss", "Dream Eater", "Drill Peck", "Drill Run", "Drum Beating",
            "Dual Chop", "Dual Wingbeat", "Dynamax Cannon", "Dynamic Punch", "Earth Power", "Earthquake",
            "Echoed Voice", "Eerie Impulse", "Eerie Spell", "Egg Bomb", "Electric Terrain", "Electrify", "Electro Ball",
            "Electro Drift", "Electroweb", "Embargo", "Ember", "Encore", "Endeavor", "Endure", "Energy Ball",
            "Entrainment", "Eruption", "Esper Wing", "Eternabeam", "Expanding Force", "Explosion", "Extrasensory",
            "Extreme Speed", "Facade", "Fairy Lock", "Fairy Wind", "Fake Out", "Fake Tears", "False Surrender",
            "False Swipe", "Feather Dance", "Feint", "Feint Attack", "Fell Stinger", "Fiery Dance", "Fiery Wrath",
            "Fillet Away", "Final Gambit", "Fire Blast", "Fire Fang", "Fire Lash", "Fire Pledge", "Fire Punch",
            "Fire Spin", "First Impression", "Fishious Rend", "Fissure", "Flail", "Flame Burst", "Flame Charge",
            "Flame Wheel", "Flamethrower", "Flare Blitz", "Flash", "Flash Cannon", "Flatter", "Fleur Cannon", "Fling",
            "Flip Turn", "Floral Healing", "Flower Shield", "Flower Trick", "Fly", "Flying Press", "Focus Blast",
            "Focus Energy", "Focus Punch", "Follow Me", "Force Palm", "Foresight", "Forest's Curse", "Foul Play",
            "Freeze-Dry", "Freeze Shock", "Freezing Glare", "Frenzy Plant", "Frost Breath", "Frustration",
            "Fury Attack", "Fury Cutter", "Fury Swipes", "Fusion Bolt", "Fusion Flare", "Future Sight", "Gastro Acid",
            "Gear Grind", "Gear Up", "Geomancy", "Giga Drain", "Giga Impact", "Gigaton Hammer", "Glacial Lance",
            "Glaciate", "Glaive Rush", "Glare", "Grass Knot", "Grass Pledge", "Grass Whistle", "Grassy Glide",
            "Grassy Terrain", "Grav Apple", "Gravity", "Growl", "Growth", "Grudge", "Guard Split", "Guard Swap",
            "Guillotine", "Gunk Shot", "Gust", "Gyro Ball", "Hail", "Hammer Arm", "Happy Hour", "Harden", "Haze",
            "Head Charge", "Head Smash", "Headbutt", "Headlong Rush", "Heal Bell", "Heal Block", "Heal Order",
            "Heal Pulse", "Healing Wish", "Heart Stamp", "Heart Swap", "Heat Crash", "Heat Wave", "Heavy Slam",
            "Helping Hand", "Hex", "Hidden Power", "High Horsepower", "High Jump Kick", "Hold Back", "Hold Hands",
            "Hone Claws", "Horn Attack", "Horn Drill", "Horn Leech", "Howl", "Hurricane", "Hydro Cannon", "Hydro Pump",
            "Hydro Steam", "Hyper Beam", "Hyper Drill", "Hyper Fang", "Hyper Voice", "Hyperspace Fury",
            "Hyperspace Hole", "Hypnosis", "Ice Ball", "Ice Beam", "Ice Burn", "Ice Fang", "Ice Hammer", "Ice Punch",
            "Ice Shard", "Ice Spinner", "Icicle Crash", "Icicle Spear", "Icy Wind", "Imprison", "Incinerate",
            "Infernal Parade", "Inferno", "Infestation", "Ingrain", "Instruct", "Ion Deluge", "Iron Defense",
            "Iron Head", "Iron Tail", "Jaw Lock", "Jet Punch", "Judgment", "Jump Kick", "Jungle Healing", "Karate Chop",
            "Kinesis", "King's Shield", "Knock Off", "Kowtow Cleave", "Land's Wrath", "Laser Focus", "Lash Out",
            "Last Resort", "Last Respects", "Lava Plume", "Leaf Blade", "Leaf Storm", "Leaf Tornado", "Leafage",
            "Leech Life", "Leech Seed", "Leer", "Lick", "Life Dew", "Light of Ruin", "Light Screen", "Liquidation",
            "Lock-On", "Lovely Kiss", "Low Kick", "Low Sweep", "Lucky Chant", "Lumina Crash", "Lunar Blessing",
            "Ancient Lunar Blessing", "Lunar Dance", "Lunge", "Luster Purge", "Mach Punch", "Magic Coat",
            "Magic Powder", "Magic Room", "Magical Leaf", "Magma Storm", "Magnet Bomb", "Magnet Rise", "Magnetic Flux",
            "Magnitude", "Make It Rain", "Mat Block", "Me First", "Mean Look", "Meditate", "Mega Drain", "Mega Kick",
            "Mega Punch", "Megahorn", "Memento", "Metal Burst", "Metal Claw", "Metal Sound", "Meteor Assault",
            "Meteor Beam", "Meteor Mash", "Metronome", "Milk Drink", "Mimic", "Mind Blown", "Mind Reader", "Minimize",
            "Miracle Eye", "Mirror Coat", "Mirror Move", "Mirror Shot", "Mist", "Mist Ball", "Misty Explosion",
            "Misty Terrain", "Moonblast", "Moongeist Beam", "Moonlight", "Morning Sun", "Mortal Spin", "Mountain Gale",
            "Mud-Slap", "Ancient Mud-Slap", "Mud Bomb", "Ancient Mud Bomb", "Mud Shot", "Mud Sport", "Muddy Water",
            "Multi-Attack", "Mystical Fire", "Mystical Power", "Nasty Plot", "Natural Gift", "Nature Power",
            "Nature's Madness", "Needle Arm", "Night Daze", "Night Shade", "Night Slash", "Nightmare", "No Retreat",
            "Noble Roar", "Nuzzle", "Oblivion Wing", "Obstruct", "Octazooka", "Ancient Octazooka", "Octolock",
            "Odor Sleuth", "Ominous Wind", "Order Up", "Origin Pulse", "Outrage", "Overdrive", "Overheat", "Pain Split",
            "Parabolic Charge", "Parting Shot", "Pay Day", "Payback", "Peck", "Perish Song", "Petal Blizzard",
            "Petal Dance", "Phantom Force", "Photon Geyser", "Pin Missile", "Plasma Fists", "Play Nice", "Play Rough",
            "Pluck", "Poison Fang", "Poison Gas", "Poison Jab", "Poison Powder", "Poison Sting", "Poison Tail",
            "Pollen Puff", "Poltergeist", "Population Bomb", "Pounce", "Pound", "Powder", "Powder Snow",
            "Power-Up Punch", "Power Gem", "Power Shift", "Power Split", "Power Swap", "Power Trick", "Power Trip",
            "Power Whip", "Precipice Blades", "Present", "Prismatic Laser", "Protect", "Psybeam", "Psyblade",
            "Psych Up", "Psychic", "Psychic Fangs", "Psychic Terrain", "Psycho Boost", "Psycho Cut", "Psycho Shift",
            "Psyshield Bash", "Psyshock", "Psystrike", "Psywave", "Punishment", "Purify", "Pursuit", "Pyro Ball",
            "Quash", "Quick Attack", "Quick Guard", "Quiver Dance", "Rage", "Rage Fist", "Rage Powder", "Raging Bull",
            "Raging Fury", "Rain Dance", "Rapid Spin", "Razor Leaf", "Razor Shell", "Razor Wind", "Recover", "Recycle",
            "Reflect", "Reflect Type", "Refresh", "Relic Song", "Rest", "Retaliate", "Return", "Revelation Dance",
            "Revenge", "Reversal", "Revival Blessing", "Rising Voltage", "Roar", "Roar of Time", "Rock Blast",
            "Rock Climb", "Rock Polish", "Rock Slide", "Rock Smash", "Rock Throw", "Rock Tomb", "Rock Wrecker",
            "Role Play", "Rolling Kick", "Rollout", "Roost", "Rototiller", "Round", "Ruination", "Sacred Fire",
            "Sacred Sword", "Safeguard", "Salt Cure", "Sand Attack", "Sand Tomb", "Sandsear Storm", "Sandstorm",
            "Scald", "Scale Shot", "Scary Face", "Scorching Sands", "Scratch", "Screech", "Searing Shot",
            "Secret Power", "Secret Sword", "Seed Bomb", "Seed Flare", "Seismic Toss", "Self-Destruct", "Shadow Ball",
            "Shadow Bone", "Shadow Claw", "Shadow Force", "Ancient Shadow Force", "Shadow Punch", "Shadow Sneak",
            "Sharpen", "Shed Tail", "Sheer Cold", "Shell Side Arm", "Shell Smash", "Shell Trap", "Shelter",
            "Ancient Shelter", "Shift Gear", "Shock Wave", "Shore Up", "Signal Beam", "Silk Trap", "Silver Wind",
            "Simple Beam", "Sing", "Sketch", "Skill Swap", "Skitter Smack", "Skull Bash", "Sky Attack", "Sky Drop",
            "Sky Uppercut", "Slack Off", "Slam", "Slash", "Sleep Powder", "Sleep Talk", "Sludge", "Sludge Bomb",
            "Sludge Wave", "Smack Down", "Smart Strike", "Smelling Salts", "Smog", "Smokescreen", "Snap Trap", "Snarl",
            "Snatch", "Snipe Shot", "Snore", "Snowscape", "Soak", "Soft-Boiled", "Solar Beam", "Solar Blade",
            "Sonic Boom", "Spacial Rend", "Spark", "Sparkling Aria", "Spectral Thief", "Speed Swap", "Spicy Extract",
            "Spider Web", "Spike Cannon", "Spikes", "Spiky Shield", "Spin Out", "Spirit Break", "Spirit Shackle",
            "Spit Up", "Spite", "Splash", "Spore", "Spotlight", "Springtide Storm", "Stealth Rock", "Steam Eruption",
            "Steamroller", "Steel Beam", "Steel Roller", "Steel Wing", "Sticky Web", "Stockpile", "Stomp",
            "Stomping Tantrum", "Stone Axe", "Stone Edge", "Stored Power", "Storm Throw", "Strange Steam", "Strength",
            "Strength Sap", "String Shot", "Struggle", "Struggle Bug", "Stuff Cheeks", "Stun Spore", "Submission",
            "Substitute", "Sucker Punch", "Sunny Day", "Sunsteel Strike", "Super Fang", "Superpower", "Supersonic",
            "Surf", "Surging Strikes", "Swagger", "Swallow", "Sweet Kiss", "Sweet Scent", "Swift", "Switcheroo",
            "Swords Dance", "Synchronoise", "Synthesis", "Tackle", "Tail Glow", "Tail Slap", "Tail Whip", "Tailwind",
            "Take Down", "Take Heart", "Tar Shot", "Taunt", "Tearful Look", "Teatime", "Techno Blast", "Teeter Dance",
            "Telekinesis", "Teleport", "Terrain Pulse", "Thief", "Thousand Arrows", "Thousand Waves", "Thrash",
            "Throat Chop", "Thunder", "Thunder Cage", "Thunder Fang", "Thunder Punch", "Thunder Shock", "Thunder Wave",
            "Thunderbolt", "Thunderous Kick", "Tickle", "Tidy Up", "Topsy-Turvy", "Torch Song", "Torment", "Toxic",
            "Toxic Spikes", "Toxic Thread", "Trailblaze", "Transform", "Tri Attack", "Trick-or-Treat", "Trick",
            "Trick Room", "Triple Arrows", "Triple Axel", "Triple Dive", "Triple Kick", "Trop Kick", "Trump Card",
            "Twin Beam", "Twineedle", "Twister", "U-turn", "Uproar", "V-Create", "Vacuum Wave", "Venom Drench",
            "Venoshock", "Victory Dance", "Vine Whip", "Vise Grip", "Vital Throw", "Volt Switch", "Volt Tackle",
            "Wake-Up Slap", "Water Gun", "Water Pledge", "Water Pulse", "Water Shuriken", "Water Sport", "Water Spout",
            "Waterfall", "Wave Crash", "Weather Ball", "Whirlpool", "Whirlwind", "Wicked Blow", "Wide Guard",
            "Wild Charge", "Wildbolt Storm", "Will-O-Wisp", "Wing Attack", "Wish", "Withdraw", "Wonder Room",
            "Wood Hammer", "Work Up", "Worry Seed", "Wrap", "Wring Out", "X-Scissor", "Yawn", "Zap Cannon",
            "Zen Headbutt", "Zing Zap", "G-Max Befuddle", "G-Max Cannonade", "G-Max Centiferno", "G-Max Chi Strike",
            "G-Max Cuddle", "G-Max Depletion", "G-Max Drum Solo", "G-Max Finale", "G-Max Fireball", "G-Max Foam Burst",
            "G-Max Gold Rush", "G-Max Gravitas", "G-Max Hydrosnipe", "G-Max Malodor", "G-Max Meltdown",
            "G-Max One Blow", "G-Max Rapid Flow", "G-Max Replenish", "G-Max Resonance", "G-Max Sandblast",
            "G-Max Smite", "G-Max Snooze", "G-Max Steelsurge", "G-Max Stonesurge", "G-Max Stun Shock",
            "G-Max Sweetness", "G-Max Tartness", "G-Max Terror", "G-Max Vine Lash", "G-Max Volcalith",
            "G-Max Volt Crash", "G-Max Wildfire", "G-Max Wind Rage", "Max Airstream", "Max Darkness", "Max Flare",
            "Max Flutterby", "Max Geyser", "Max Guard", "Max Hailstorm", "Max Knuckle", "Max Lightning",
            "Max Mindstorm", "Max Ooze", "Max Overgrowth", "Max Phantasm", "Max Quake", "Max Rockfall", "Max Starfall",
            "Max Steelspike", "Max Strike", "Max Wyrmwind", "10,000,000 Volt Thunderbolt", "Acid Downpour",
            "All-Out Pummeling", "Black Hole Eclipse", "Bloom Doom", "Breakneck Blitz", "Catastropika",
            "Clangorous Soulblaze", "Continental Crush", "Corkscrew Crash", "Devastating Drake", "Extreme Evoboost",
            "Genesis Supernova", "Gigavolt Havoc", "Guardian of Alola", "Hydro Vortex", "Inferno Overdrive",
            "Let's Snuggle Forever", "Light That Burns the Sky", "Malicious Moonsault", "Menacing Moonraze Maelstrom",
            "Never-Ending Nightmare", "Oceanic Operetta", "Pulverizing Pancake", "Savage Spin-Out",
            "Searing Sunraze Smash", "Shattered Psyche", "Sinister Arrow Raid", "Soul-Stealing 7-Star Strike",
            "Splintered Stormshards", "Stoked Sparksurfer", "Subzero Slammer", "Supersonic Skystrike", "Tectonic Rage",
            "Twinkle Tackle"));

    public static final ArrayList<String> pokemon_list = new ArrayList<>(Arrays.asList(
            "Abomasnow", "Abra", "Absol", "Accelgor", "Aegislash", "Aerodactyl", "Aggron", "Aipom", "Alakazam",
            "Alcremie", "Alolan Diglett", "Alolan Dugtrio", "Alolan Exeggutor", "Alolan Geodude", "Alolan Golem",
            "Alolan Graveler", "Alolan Grimer", "Alolan Marowak", "Alolan Meowth", "Alolan Muk", "Alolan Ninetales",
            "Alolan Persian", "Alolan Raichu", "Alolan Raticate", "Alolan Rattata", "Alolan Sandshrew",
            "Alolan Sandslash", "Alolan Vulpix", "Alomomola", "Altaria", "Amaura", "Ambipom", "Amoonguss",
            "Amped Toxtricity", "Ampharos", "Annihilape", "Anorith", "Appletun", "Applin", "Araquanid", "Arbok",
            "Arboliva", "Arcanine", "Arceus", "Archen", "Archeops", "Arctibax", "Arctovish", "Arctozolt", "Ariados",
            "Armaldo", "Armarouge", "Aromatisse", "Aron", "Arrokuda", "Articuno", "Ash Greninja", "Attack Deoxys",
            "Audino", "Aurorus", "Autumn Deerling", "Autumn Sawsbuck", "Avalugg", "Axew", "Az Floette", "Azelf",
            "Azumarill", "Azurill", "Bagon", "Baltoy", "Banette", "Barbaracle", "Barboach", "Barraskewda",
            "Basculegion", "Basculin", "Bastiodon", "Battle Bond Greninja", "Baxcalibur", "Bayleef", "Beartic",
            "Beautifly", "Beedrill", "Beheeyem", "Beldum", "Belle Pikachu", "Bellibolt", "Bellossom", "Bellsprout",
            "Bergmite", "Bewear", "Bibarel", "Bidoof", "Binacle", "Bisharp", "Blacephalon", "Black Kyurem",
            "Blade Aegislash", "Blastoise", "Blaziken", "Blipbug", "Blissey", "Blitzle", "Blue Basculin",
            "Blue Squawkabilly", "Boldore", "Boltund", "Bombirdier", "Bonsly", "Bouffalant", "Bounsweet", "Braixen",
            "Brambleghast", "Bramblin", "Braviary", "Breloom", "Brionne", "Bronzong", "Bronzor", "Brute Bonnet",
            "Bruxish", "Budew", "Buizel", "Bulbasaur", "Buneary", "Bunnelby", "Burmy", "Burn Genesect",
            "Busted Mimikyu", "Butterfree", "Buzzwole", "Cacnea", "Cacturne", "Calyrex", "Camerupt", "Capsakid",
            "Carbink", "Carkol", "Carnivine", "Carracosta", "Carvanha", "Cascoon", "Castform", "Caterpie", "Celebi",
            "Celesteela", "Centiskorch", "Ceruledge", "Cetitan", "Cetoddle", "Chandelure", "Chansey", "Charcadet",
            "Charizard", "Charjabug", "Charmander", "Charmeleon", "Chatot", "Cherrim", "Cherubi", "Chesnaught",
            "Chespin", "Chewtle", "Chi-Yu", "Chien-Pao", "Chikorita", "Chill Genesect", "Chimchar", "Chimecho",
            "Chinchou", "Chingling", "Cinccino", "Cinderace", "Clamperl", "Clauncher", "Clawitzer", "Claydol",
            "Clefable", "Clefairy", "Cleffa", "Clobbopus", "Clodsire", "Cloyster", "Coalossal", "Cobalion",
            "Cofagrigus", "Combee", "Combusken", "Comfey", "Complete Zygarde", "Conkeldurr", "Copperajah",
            "Core Minior", "Corphish", "Corsola", "Corviknight", "Corvisquire", "Cosmoem", "Cosmog", "Cosplay Pikachu",
            "Cottonee", "Crabominable", "Crabrawler", "Cradily", "Cramorant", "Cranidos", "Crawdaunt", "Cresselia",
            "Croagunk", "Crobat", "Crocalor", "Croconaw", "Crowned Sword Zacian", "Crowned Sword Zamazenta", "Crustle",
            "Cryogonal", "Cubchoo", "Cubone", "Cufant", "Cursola", "Cutiefly", "Cyclizar", "Cyndaquil", "Dachsbun",
            "Darkrai", "Darmanitan", "Dartrix", "Darumaka", "Dawn Wings Necrozma", "Decidueye", "Dedenne", "Deerling",
            "Defense Deoxys", "Deino", "Delcatty", "Delibird", "Delphox", "Deoxys", "Dewgong", "Dewott", "Dewpider",
            "Dhelmise", "Dialga", "Diancie", "Diggersby", "Diglett", "Ditto", "Dodrio", "Doduo", "Dolliv", "Dondozo",
            "Donphan", "Dottler", "Doublade", "Douse Genesect", "Dracovish", "Dracozolt", "Dragalge", "Dragapult",
            "Dragonair", "Dragonite", "Drakloak", "Drampa", "Drapion", "Dratini", "Drednaw", "Dreepy", "Drifblim",
            "Drifloon", "Drilbur", "Drizzile", "Droopy Tatsugiri", "Drowzee", "Druddigon", "Dubwool", "Ducklett",
            "Dudunsparce", "Dugtrio", "Dunsparce", "Duosion", "Duraludon", "Durant", "Dusclops", "Dusk Lycanroc",
            "Dusk Mane Necrozma", "Dusknoir", "Duskull", "Dustox", "Dwebble", "East Gastrodon", "East Shellos",
            "Eelektrik", "Eelektross", "Eevee", "Eiscue", "Ekans", "Eldegoss", "Electabuzz", "Electivire", "Electrike",
            "Electrode", "Elekid", "Elgyem", "Emboar", "Emolga", "Empoleon", "Enamorus", "Entei", "Escavalier",
            "Espathra", "Espeon", "Espurr", "Eternamax Eternatus", "Eternatus", "Excadrill", "Exeggcute", "Exeggutor",
            "Exploud", "Falinks", "Family Three Maushold", "Fan Rotom", "Farfetchd", "Farigiraf", "Fearow", "Feebas",
            "Female Basculegion", "Female Indeedee", "Female Oinkologne", "Fennekin", "Feraligatr", "Ferroseed",
            "Ferrothorn", "Fidough", "Finizen", "Finneon", "Flaaffy", "Flabebe", "Flamigo", "Flapple", "Flareon",
            "Fletchinder", "Fletchling", "Flittle", "Floatzel", "Floette", "Floragato", "Florges", "Flutter Mane",
            "Flygon", "Fomantis", "Foongus", "Forretress", "Fraxure", "Frigibax", "Frillish", "Froakie", "Frogadier",
            "Froslass", "Frosmoth", "Frost Rotom", "Fuecoco", "Full Moon Lunala", "Furfrou", "Furret", "Gabite",
            "Galarian Articuno", "Galarian Corsola", "Galarian Darmanitan", "Galarian Darumaka", "Galarian Farfetchd",
            "Galarian Linoone", "Galarian Meowth", "Galarian Moltres", "Galarian Mr Mime", "Galarian Ponyta",
            "Galarian Rapidash", "Galarian Slowbro", "Galarian Slowking", "Galarian Slowpoke", "Galarian Stunfisk",
            "Galarian Weezing", "Galarian Yamask", "Galarian Zapdos", "Galarian Zen Mode Darmanitan",
            "Galarian Zigzagoon", "Gallade", "Galvantula", "Garbodor", "Garchomp", "Gardevoir", "Garganacl", "Gastly",
            "Gastrodon", "Genesect", "Gengar", "Geodude", "Gholdengo", "Gible", "Gigalith", "Gigantamax Alcremie",
            "Gigantamax Appletun", "Gigantamax Blastoise", "Gigantamax Butterfree", "Gigantamax Centiskorch",
            "Gigantamax Charizard", "Gigantamax Cinderace", "Gigantamax Coalossal", "Gigantamax Copperajah",
            "Gigantamax Corviknight", "Gigantamax Drednaw", "Gigantamax Duraludon", "Gigantamax Eevee",
            "Gigantamax Flapple", "Gigantamax Garbodor", "Gigantamax Gengar", "Gigantamax Grimmsnarl",
            "Gigantamax Hatterene", "Gigantamax Inteleon", "Gigantamax Kingler", "Gigantamax Lapras",
            "Gigantamax Machamp", "Gigantamax Melmetal", "Gigantamax Meowth", "Gigantamax Orbeetle",
            "Gigantamax Pikachu", "Gigantamax RS Urshifu", "Gigantamax Rillaboom", "Gigantamax SS Urshifu",
            "Gigantamax Sandaconda", "Gigantamax Snorlax", "Gigantamax Toxtricity", "Gigantamax Venusaur", "Gimmighoul",
            "Girafarig", "Giratina", "Glaceon", "Glalie", "Glameow", "Glastrier", "Gligar", "Glimmet", "Glimmora",
            "Gliscor", "Gloom", "Gogoat", "Golbat", "Goldeen", "Golduck", "Golem", "Golett", "Golisopod", "Golurk",
            "Goodra", "Goomy", "Gorebyss", "Gorging Cramorant", "Gossifleur", "Gothita", "Gothitelle", "Gothorita",
            "Gourgeist", "Grafaiai", "Granbull", "Grapploct", "Graveler", "Great Tusk", "Greavard", "Greedent",
            "Greninja", "Grimer", "Grimmsnarl", "Grookey", "Grotle", "Groudon", "Grovyle", "Growlithe", "Grubbin",
            "Grumpig", "Gulpin", "Gulping Cramorant", "Gumshoos", "Gurdurr", "Guzzlord", "Gyarados", "Hakamo-o",
            "Hangry Morpeko", "Happiny", "Hariyama", "Hatenna", "Hatterene", "Hattrem", "Haunter", "Hawlucha",
            "Haxorus", "Heat Rotom", "Heatmor", "Heatran", "Heliolisk", "Helioptile", "Heracross", "Herdier",
            "Hero Palafin", "Hippopotas", "Hippowdon", "Hisuian Arcanine", "Hisuian Avalugg", "Hisuian Braviary",
            "Hisuian Decidueye", "Hisuian Electrode", "Hisuian Goodra", "Hisuian Growlithe", "Hisuian Lilligant",
            "Hisuian Qwilfish", "Hisuian Samurott", "Hisuian Sliggoo", "Hisuian Sneasel", "Hisuian Typhlosion",
            "Hisuian Voltorb", "Hisuian Zoroark", "Hisuian Zorua", "Hitmonchan", "Hitmonlee", "Hitmontop", "Ho-Oh",
            "Honchkrow", "Honedge", "Hoopa", "Hoothoot", "Hoppip", "Horsea", "Houndoom", "Houndour", "Houndstone",
            "Huntail", "Hydreigon", "Hypno", "Ice Castform", "Ice Rider Calyrex", "Igglybuff", "Illumise", "Impidimp",
            "Incineroar", "Indeedee", "Infernape", "Inkay", "Inteleon", "Iron Bundle", "Iron Hands", "Iron Jugulis",
            "Iron Leaves", "Iron Moth", "Iron Thorns", "Iron Treads", "Iron Valiant", "Ivysaur", "Jangmo-o",
            "Jellicent", "Jigglypuff", "Jirachi", "Jolteon", "Joltik", "Jumpluff", "Jynx", "Kabuto", "Kabutops",
            "Kadabra", "Kakuna", "Kangaskhan", "Karrablast", "Kartana", "Kecleon", "Keldeo", "Kilowattrel", "Kingambit",
            "Kingdra", "Kingler", "Kirlia", "Klang", "Klawf", "Kleavor", "Klefki", "Klink", "Klinklang", "Koffing",
            "Komala", "Kommo-o", "Koraidon", "Krabby", "Kricketot", "Kricketune", "Krokorok", "Krookodile", "Kubfu",
            "Kyogre", "Kyurem", "Lairon", "Lampent", "Landorus", "Lanturn", "Lapras", "Larvesta", "Larvitar", "Latias",
            "Latios", "Leafeon", "Leavanny", "Lechonk", "Ledian", "Ledyba", "Lickilicky", "Lickitung", "Liepard",
            "Lileep", "Lilligant", "Lillipup", "Linoone", "Litleo", "Litten", "Litwick", "Lokix", "Lombre", "Lopunny",
            "Lotad", "Loudred", "Lucario", "Ludicolo", "Lugia", "Lumineon", "Lunala", "Lunatone", "Lurantis", "Luvdisc",
            "Luxio", "Luxray", "Lycanroc", "Mabosstiff", "Machamp", "Machoke", "Machop", "Magby", "Magcargo",
            "Magearna", "Magikarp", "Magmar", "Magmortar", "Magnemite", "Magneton", "Magnezone", "Makuhita", "Malamar",
            "Mamoswine", "Manaphy", "Mandibuzz", "Manectric", "Mankey", "Mantine", "Mantyke", "Maractus", "Mareanie",
            "Mareep", "Marill", "Marowak", "Marshadow", "Marshtomp", "Maschiff", "Masquerain", "Maushold", "Mawile",
            "Medicham", "Meditite", "Mega Abomasnow", "Mega Absol", "Mega Aerodactyl", "Mega Aggron", "Mega Alakazam",
            "Mega Altaria", "Mega Ampharos", "Mega Audino", "Mega Banette", "Mega Beedrill", "Mega Blastoise",
            "Mega Blaziken", "Mega Camerupt", "Mega Diancie", "Mega Gallade", "Mega Garchomp", "Mega Gardevoir",
            "Mega Gengar", "Mega Glalie", "Mega Gyarados", "Mega Heracross", "Mega Houndoom", "Mega Kangaskhan",
            "Mega Latias", "Mega Latios", "Mega Lopunny", "Mega Lucario", "Mega Manectric", "Mega Mawile",
            "Mega Medicham", "Mega Metagross", "Mega Pidgeot", "Mega Pinsir", "Mega Rayquaza", "Mega Sableye",
            "Mega Salamence", "Mega Sceptile", "Mega Scizor", "Mega Sharpedo", "Mega Slowbro", "Mega Steelix",
            "Mega Swampert", "Mega Tyranitar", "Mega Venusaur", "Mega X Charizard", "Mega X Mewtwo", "Mega Y Charizard",
            "Mega Y Mewtwo", "Meganium", "Melmetal", "Meloetta", "Meltan", "Meowscarada", "Meowstic", "Meowth",
            "Mesprit", "Metagross", "Metang", "Metapod", "Mew", "Mewtwo", "Midnight Lycanroc", "Mienfoo", "Mienshao",
            "Mightyena", "Milcery", "Milotic", "Miltank", "Mime Jr", "Mimikyu", "Minccino", "Minior", "Minun",
            "Miraidon", "Misdreavus", "Mismagius", "Moltres", "Monferno", "Morelull", "Morgrem", "Morpeko", "Mothim",
            "Mow Rotom", "Mr Mime", "Mr Rime", "Mudbray", "Mudkip", "Mudsdale", "Muk", "Munchlax", "Munna", "Murkrow",
            "Musharna", "Nacli", "Naclstack", "Naganadel", "Natu", "Necrozma", "Neutral Xerneas", "Nickit", "Nidoking",
            "Nidoqueen", "Nidoranfemale", "Nidoranmale", "Nidorina", "Nidorino", "Nihilego", "Nincada", "Ninetales",
            "Ninjask", "Noctowl", "Noibat", "Noice Face Eiscue", "Noivern", "Nosepass", "Numel", "Nuzleaf", "Nymble",
            "Obstagoon", "Octillery", "Oddish", "Oinkologne", "Omanyte", "Omastar", "Onix", "Oranguru", "Orbeetle",
            "Oricorio", "Origin Dialga", "Origin Giratina", "Origin Palkia", "Original Color Magearna", "Orthworm",
            "Oshawott", "Overqwil", "Pachirisu", "Palafin", "Paldean Aqua Tauros", "Paldean Blaze Tauros",
            "Paldean Combat Tauros", "Paldean Wooper", "Palkia", "Palossand", "Palpitoad", "Pancham", "Pangoro",
            "Panpour", "Pansage", "Pansear", "Paras", "Parasect", "Passimian", "Patrat", "Pau Oricorio", "Pawmi",
            "Pawmo", "Pawmot", "Pawniard", "Pelipper", "Perrserker", "Persian", "Petilil", "Phanpy", "Phantump",
            "Phd Pikachu", "Pheromosa", "Phione", "Phony Polteageist", "Phony Sinistea", "Pichu", "Pidgeot",
            "Pidgeotto", "Pidgey", "Pidove", "Pignite", "Pikachu", "Pikipek", "Piloswine", "Pincurchin", "Pineco",
            "Pinsir", "Piplup", "Pirouette Meloetta", "Plusle", "Poipole", "Politoed", "Poliwag", "Poliwhirl",
            "Poliwrath", "Polteageist", "Pompom Oricorio", "Ponyta", "Poochyena", "Popplio", "Popstar Pikachu",
            "Porygon", "Porygon-Z", "Porygon2", "Primal Groudon", "Primal Kyogre", "Primarina", "Primeape", "Prinplup",
            "Probopass", "Psyduck", "Pumpkaboo", "Pupitar", "Purrloin", "Purugly", "Pyroar", "Pyukumuku", "Quagsire",
            "Quaquaval", "Quaxly", "Quaxwell", "Quilava", "Quilladin", "Qwilfish", "Raboot", "Rabsca",
            "Radiant Sun Solgaleo", "Raichu", "Raikou", "Rain Castform", "Ralts", "Rampardos", "Rapid Strike Urshifu",
            "Rapidash", "Raticate", "Rattata", "Rayquaza", "Regice", "Regidrago", "Regieleki", "Regigigas", "Regirock",
            "Registeel", "Relicanth", "Rellor", "Remoraid", "Reshiram", "Resolute Keldeo", "Reuniclus", "Revavroom",
            "Rhydon", "Rhyhorn", "Rhyperior", "Ribombee", "Rillaboom", "Riolu", "Roaming Gimmighoul", "Roaring Moon",
            "Rockruff", "Rockstar Pikachu", "Roggenrola", "Rolycoly", "Rookidee", "Roselia", "Roserade", "Rotom",
            "Rowlet", "Rufflet", "Runerigus", "Sableye", "Salamence", "Salandit", "Salazzle", "Samurott", "Sandaconda",
            "Sandile", "Sandshrew", "Sandslash", "Sandy Burmy", "Sandy Shocks", "Sandy Wormadam", "Sandygast", "Sawk",
            "Sawsbuck", "Scatterbug", "Sceptile", "School Wishiwashi", "Scizor", "Scolipede", "Scorbunny", "Scovillain",
            "Scrafty", "Scraggy", "Scream Tail", "Scyther", "Seadra", "Seaking", "Sealeo", "Seedot", "Seel",
            "Seismitoad", "Sensu Oricorio", "Sentret", "Serperior", "Servine", "Seviper", "Sewaddle",
            "Shadow Rider Calyrex", "Sharpedo", "Shaymin", "Shedinja", "Shelgon", "Shellder", "Shellos", "Shelmet",
            "Shieldon", "Shiftry", "Shiinotic", "Shinx", "Shock Genesect", "Shroodle", "Shroomish", "Shuckle",
            "Shuppet", "Sigilyph", "Silcoon", "Silicobra", "Silvally", "Simipour", "Simisage", "Simisear", "Sinistea",
            "Sirfetchd", "Sizzlipede", "Skarmory", "Skeledirge", "Skiddo", "Skiploom", "Skitty", "Skorupi", "Skrelp",
            "Skuntank", "Skwovet", "Sky Shaymin", "Slaking", "Slakoth", "Sliggoo", "Slither Wing", "Slowbro",
            "Slowking", "Slowpoke", "Slugma", "Slurpuff", "Smeargle", "Smoliv", "Smoochum", "Sneasel", "Sneasler",
            "Snivy", "Snom", "Snorlax", "Snorunt", "Snover", "Snubbull", "Sobble", "Solgaleo", "Solosis", "Solrock",
            "Spearow", "Spectrier", "Speed Deoxys", "Spewpa", "Spheal", "Spidops", "Spiky Pichu", "Spinarak", "Spinda",
            "Spiritomb", "Spoink", "Sprigatito", "Spritzee", "Squawkabilly", "Squirtle", "Stakataka", "Stantler",
            "Staraptor", "Staravia", "Starly", "Starmie", "Staryu", "Steelix", "Steenee", "Stonjourner", "Stoutland",
            "Stretchy Tatsugiri", "Stufful", "Stunfisk", "Stunky", "Sudowoodo", "Suicune", "Summer Deerling",
            "Summer Sawsbuck", "Sun Castform", "Sunflora", "Sunkern", "Sunshine Cherrim", "Surskit", "Sus Deoxys",
            "Swablu", "Swadloon", "Swalot", "Swampert", "Swanna", "Swellow", "Swinub", "Swirlix", "Swoobat", "Sylveon",
            "Tadbulb", "Taillow", "Talonflame", "Tandemaus", "Tangela", "Tangrowth", "Tapu Bulu", "Tapu Fini",
            "Tapu Koko", "Tapu Lele", "Tarountula", "Tatsugiri", "Tauros", "Teddiursa", "Ten Percent Zygarde",
            "Tentacool", "Tentacruel", "Tepig", "Terrakion", "Therian Enamorus", "Therian Landorus",
            "Therian Thundurus", "Therian Tornadus", "Thievul", "Three Segment Dudunsparce", "Throh", "Thundurus",
            "Thwackey", "Timburr", "Ting-Lu", "Tinkatink", "Tinkaton", "Tinkatuff", "Tirtouga", "Toedscool",
            "Toedscruel", "Togedemaru", "Togekiss", "Togepi", "Togetic", "Torchic", "Torkoal", "Tornadus", "Torracat",
            "Torterra", "Totodile", "Toucannon", "Toxapex", "Toxel", "Toxicroak", "Toxtricity", "Tranquill", "Trapinch",
            "Trash Burmy", "Trash Wormadam", "Treecko", "Trevenant", "Tropius", "Trubbish", "Trumbeak", "Tsareena",
            "Turtonator", "Turtwig", "Tympole", "Tynamo", "Type Null", "Typhlosion", "Tyranitar", "Tyrantrum",
            "Tyrogue", "Tyrunt", "Ultra Necrozma", "Umbreon", "Unbound Hoopa", "Unfezant", "Unown", "Ursaluna",
            "Ursaring", "Urshifu", "Uxie", "Vanillish", "Vanillite", "Vanilluxe", "Vaporeon", "Varoom", "Veluza",
            "Venipede", "Venomoth", "Venonat", "Venusaur", "Vespiquen", "Vibrava", "Victini", "Victreebel", "Vigoroth",
            "Vikavolt", "Vileplume", "Virizion", "Vivillon", "Volbeat", "Volcanion", "Volcarona", "Voltorb", "Vullaby",
            "Vulpix", "Wailmer", "Wailord", "Walking Wake", "Walrein", "Wartortle", "Wash Rotom", "Watchog", "Wattrel",
            "Weavile", "Weedle", "Weepinbell", "Weezing", "Whimsicott", "Whirlipede", "Whiscash", "Whismur",
            "White Basculin", "White Kyurem", "White Squawkabilly", "Wigglytuff", "Wiglett", "Wimpod", "Wingull",
            "Winter Deerling", "Winter Sawsbuck", "Wishiwashi", "Wo-Chien", "Wobbuffet", "Woobat", "Wooloo", "Wooper",
            "Wormadam", "Wugtrio", "Wurmple", "Wynaut", "Wyrdeer", "Xatu", "Xerneas", "Xurkitree", "Yamask", "Yamper",
            "Yanma", "Yanmega", "Yellow Squawkabilly", "Yungoos", "Yveltal", "Zacian", "Zamazenta", "Zangoose",
            "Zapdos", "Zarude", "Zebstrika", "Zekrom", "Zen Mode Darmanitan", "Zenith Marshadow", "Zeraora",
            "Zigzagoon", "Zoroark", "Zorua", "Zubat", "Zweilous", "Zygarde"));

}
